LABELS_MAPPINGS = {
    "true": True,
    "half-true": True,
    "mostly-true": True,
    "barely-true": False,
    "pants-fire": False,
    "false": False,
}

STATES_MAPPINGS = {
    "rhode island": "rhode island",
    "tennesse": "tennessee",
    "tex": "texas",
    "virgiia": "virginia",
    "virgina": "virginia",
    "virginia director, coalition to stop gun violence": "virginia",
    "ohio": "ohio",
    "pa - pennsylvania": "pennsylvania",
    "washington dc": "washington d.c.",
    "washington, d.c.": "washington d.c.",
    "district of columbia": "washington d.c.",
    "washington state": "washington",
    "the united states": "united states"
}

JOBS_MAPPINGS = {
    "president": "president",
    "president-elect": "president-elect",
    "former president": "former president",
    "u.s. senator": "u.s. senator",
    "u.s. senator from ohio": "u.s. senator",
    "governor": "governor",
    "former governor": "former governor",
    "governor of new jersey": "governor of new jersey",
    "governor of ohio as of jan. 10, 2011": "governor of ohio",
    "presidential candidate": "presidential candidate",
    "u.s. representative": "u.s. representative",
    "u.s. representative, florida district 23": "u.s. representative",
    "u.s. representative, florida district 22": "u.s. representative",
    "u.s. house of representatives": "u.s. representative",
    "u.s. house member": "u.s. representative",
    "state senator": "state senator",
    "state representative": "state representative",
    "congressman": "congressman",
    "congresswoman": "congresswoman",
    "milwaukee county executive": "milwaukee county executive",
    "candidate for u.s. senate and physician": "candidate for u.s. senate",
    "state assemblyman": "state assemblyman",
    "house majority leader": "house majority leader",
    "house minority leader": "house minority leader",
    "senate minority leader": "senate minority leader",
    "senate democratic leader": "senate democratic leader",
    "speaker of the house of representatives": "speaker of the house of representatives",
    "lieutenant governor": "lieutenant governor",
    "lieutenant governor-elect": "lieutenant governor-elect",
    "attorney": "attorney",
    "attorney general": "attorney general",
    "lawyer": "lawyer",
    "social media posting": "social media posting",
    "co-host on cnn\"s \"crossfire\"": "co-host on cnn's crossfire",
    "msnbc host": "msnbc host",
    "radio host": "radio host",
    "columnist": "columnist",
    "businessman": "businessman",
    "author": "author",
    "actor": "actor",
    "consultant": "consultant",
    "secretary of state": "secretary of state",
    "madison school board member": "madison school board member",
    "ohio treasurer": "ohio treasurer",
    "chairman, republican national committee": "chairman, republican national committee",
    "former mayor of houston": "former mayor of houston",
    "mayor of providence": "mayor of providence",
    "mayor of milwaukee": "mayor of milwaukee",
    "conservative advocacy group": "conservative advocacy group",
    "political action committee": "political action committee",
}